import "./globals.css";
import { Montserrat } from "next/font/google";
import QueryWrapper from "./QueryWrapper";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} p-20`}>
        <QueryWrapper>{children}</QueryWrapper>
      </body>
    </html>
  );
}
